export const PAISES_LATAM = [
  'Venezuela',
  'Colombia',
  'Perú',
  'Ecuador',
  'Bolivia',
  'Chile',
  'Argentina',
  'Uruguay',
  'Paraguay',
  'Brasil',
  'México',
  'Guatemala',
  'Honduras',
  'El Salvador',
  'Nicaragua',
  'Costa Rica',
  'Panamá',
  'República Dominicana',
  'Cuba',
  'Puerto Rico',
  'Trinidad y Tobago',
  'Jamaica',
];
